export const GET_WXMP_LIST = 'GET_WXMP_LIST'
export const GET_WXMPLIST_FAILURE = 'GET_WXMPLIST_FAILURE'

export const GET_USER_INFO = 'GET_USER_INFO'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'

export const GET_WXMP_DETAIL = 'GET_WXMP_DETAIL'
export const UPDATE_WXMP_DETAIL = 'UPDATE_WXMP_DETAIL'

export const SHOW_TOAST = 'SHOW_TOAST'
export const HIDE_TOAST = 'HIDE_TOAST'

export const GET_WXTOKEN = 'GET_WXTOKEN'
export const LOGOUT = 'LOGOUT'
